# Generated by Django 6.0.6 on 2026-06-12 10:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interview_type', models.CharField(choices=[('hr', 'HR Interview'), ('behavioural', 'Behavioural Interview'), ('technical', 'Technical Interview'), ('mock', 'Mock Interview')], max_length=20)),
                ('domain', models.CharField(default='general', max_length=50)),
                ('total_questions', models.PositiveSmallIntegerField(default=0)),
                ('questions_answered', models.PositiveSmallIntegerField(default=0)),
                ('overall_score', models.PositiveSmallIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_id', models.CharField(max_length=20)),
                ('question_text', models.TextField()),
                ('response_text', models.TextField()),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('feedback', models.JSONField(default=list)),
                ('word_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='interview_coach.interviewsession')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('session', 'question_id')},
            },
        ),
    ]
