# Generated by Django 6.0.6 on 2026-06-12 10:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='My Resume', max_length=200)),
                ('template', models.CharField(default='modern_clean', max_length=50)),
                ('personal_info', models.JSONField(default=dict)),
                ('summary', models.TextField(blank=True)),
                ('target_domain', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ATSAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_description', models.TextField(blank=True)),
                ('domain', models.CharField(default='technology', max_length=50)),
                ('ats_score', models.PositiveSmallIntegerField(default=0)),
                ('grade', models.CharField(default='D', max_length=2)),
                ('breakdown', models.JSONField(default=dict)),
                ('matched_keywords', models.JSONField(default=list)),
                ('missing_keywords', models.JSONField(default=list)),
                ('suggestions', models.JSONField(default=list)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_analyses', to='resume_builder.resume')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_type', models.CharField(choices=[('experience', 'Work Experience'), ('education', 'Education'), ('skills', 'Skills'), ('projects', 'Projects'), ('certifications', 'Certifications'), ('achievements', 'Achievements'), ('languages', 'Languages'), ('custom', 'Custom')], max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('content', models.JSONField(default=list)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='resume_builder.resume')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
