# Generated by Django 6.0.6 on 2026-06-12 10:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('value_description', models.CharField(max_length=300)),
                ('value_inr', models.PositiveIntegerField(blank=True, null=True)),
                ('value_usd', models.PositiveIntegerField(blank=True, null=True)),
                ('eligibility', models.JSONField(default=list)),
                ('fields_of_study', models.JSONField(default=list)),
                ('deadline_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_merit_based', models.BooleanField(default=True)),
                ('is_need_based', models.BooleanField(default=False)),
                ('is_renewable', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('university_type', models.CharField(choices=[('engineering', 'Engineering'), ('medical', 'Medical'), ('management', 'Management'), ('law', 'Law'), ('arts_science', 'Arts & Science'), ('general', 'General'), ('foreign', 'Foreign University')], max_length=30)),
                ('country', models.CharField(default='India', max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('nirf_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('qs_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('naac_grade', models.CharField(blank=True, max_length=10)),
                ('established', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fees_per_year_inr', models.PositiveIntegerField(blank=True, null=True)),
                ('tuition_per_year_usd', models.PositiveIntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('notable_for', models.JSONField(default=list)),
                ('entrance_exams', models.JSONField(default=list)),
                ('placements', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'ordering': ['nirf_rank', 'qs_rank', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('preparing', 'Preparing'), ('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('awarded', 'Awarded')], default='saved', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.scholarship')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('student', 'scholarship')},
            },
        ),
    ]
