# Generated by Django 6.0.6 on 2026-06-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('counsellor', 'Counsellor'), ('admin', 'Admin'), ('school_admin', 'School Admin'), ('recruiter', 'Recruiter'), ('parent', 'Parent'), ('enterprise', 'Enterprise')], default='student', max_length=20),
        ),
    ]
