# Generated by Django 6.0.6 on 2026-06-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_score', models.PositiveIntegerField(default=0)),
                ('ai_career_recommendations', models.JSONField(blank=True, default=list)),
                ('skill_gaps', models.JSONField(blank=True, default=list)),
                ('recommended_courses', models.JSONField(blank=True, default=list)),
                ('career_roadmap', models.JSONField(blank=True, default=dict)),
                ('personality_type', models.CharField(blank=True, max_length=10)),
                ('assessment_completed', models.BooleanField(default=False)),
                ('last_ai_analysis', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='pending', max_length=20)),
                ('is_ai_suggested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['target_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_education', models.CharField(blank=True, choices=[('class_9_10', 'Class 9-10'), ('class_11_12', 'Class 11-12'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('graduate', 'Graduate (Working)'), ('professional', 'Working Professional'), ('other', 'Other')], max_length=30)),
                ('stream', models.CharField(blank=True, choices=[('science_pcm', 'Science (PCM)'), ('science_pcb', 'Science (PCB)'), ('science_pcmb', 'Science (PCMB)'), ('commerce', 'Commerce'), ('arts', 'Arts / Humanities'), ('vocational', 'Vocational'), ('other', 'Other')], max_length=30)),
                ('institution_name', models.CharField(blank=True, max_length=300)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('percentage_cgpa', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('career_interests', models.JSONField(blank=True, default=list)),
                ('preferred_industries', models.JSONField(blank=True, default=list)),
                ('target_roles', models.JSONField(blank=True, default=list)),
                ('technical_skills', models.JSONField(blank=True, default=list)),
                ('soft_skills', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('short_term_goal', models.TextField(blank=True)),
                ('long_term_goal', models.TextField(blank=True)),
                ('preferred_work_style', models.CharField(blank=True, max_length=50)),
                ('salary_expectation', models.CharField(blank=True, max_length=100)),
                ('study_abroad_interest', models.BooleanField(default=False)),
                ('profile_score', models.PositiveIntegerField(default=0)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
            },
        ),
    ]
