"""initial_schema

Revision ID: fcc6ee0db043
Revises: 
Create Date: 2026-07-04 12:30:48.102966

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc6ee0db043'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colleges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('country', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('streams', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('min_score', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('annual_fees', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ranking', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('placement_score', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('website', sa.String(length=255), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=180),
               type_=sa.String(length=220),
               existing_nullable=False)
        batch_op.alter_column('courses',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.alter_column('entrance_exam',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_colleges_location'))
        batch_op.create_index(batch_op.f('ix_colleges_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_colleges_state'), ['state'], unique=False)
        batch_op.drop_column('fees_min')
        batch_op.drop_column('rating')
        batch_op.drop_column('fees_max')
        batch_op.drop_column('location')

    with op.batch_alter_table('guidance_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_minutes', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('meeting_link', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guidance_sessions', schema=None) as batch_op:
        batch_op.drop_column('meeting_link')
        batch_op.drop_column('duration_minutes')

    with op.batch_alter_table('colleges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('fees_max', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('fees_min', sa.INTEGER(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_colleges_state'))
        batch_op.drop_index(batch_op.f('ix_colleges_city'))
        batch_op.create_index(batch_op.f('ix_colleges_location'), ['location'], unique=False)
        batch_op.alter_column('entrance_exam',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('courses',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=220),
               type_=sa.VARCHAR(length=180),
               existing_nullable=False)
        batch_op.drop_column('website')
        batch_op.drop_column('placement_score')
        batch_op.drop_column('ranking')
        batch_op.drop_column('annual_fees')
        batch_op.drop_column('min_score')
        batch_op.drop_column('streams')
        batch_op.drop_column('country')
        batch_op.drop_column('state')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
