# Generated by Django 6.0.6 on 2026-06-12 09:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('register', 'Register'), ('login', 'Login'), ('logout', 'Logout'), ('password_reset', 'Password Reset'), ('profile_update', 'Profile Update'), ('session_booked', 'Session Booked'), ('session_cancelled', 'Session Cancelled'), ('ai_query', 'AI Query'), ('admin_action', 'Admin Action')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('session_confirmed', 'Session Confirmed'), ('session_reminder', 'Session Reminder'), ('session_cancelled', 'Session Cancelled'), ('profile_complete', 'Profile Complete'), ('new_recommendation', 'New Recommendation'), ('counsellor_message', 'Counsellor Message'), ('system', 'System')], default='system', max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
