"""
University, program, scholarship, and exam cutoff data for Phase 6.
"""

INDIAN_UNIVERSITIES = [
    {"slug": "iit-bombay", "name": "IIT Bombay", "type": "engineering", "location": "Mumbai, Maharashtra",
     "nirf_rank": 3, "naac_grade": "A++", "established": 1958, "fees_per_year_inr": 220000,
     "website": "https://www.iitb.ac.in", "notable_for": ["CS", "Electrical", "Mechanical", "Chemical"],
     "placements": {"avg_package_lpa": 25, "highest_package_lpa": 2100, "placement_pct": 95},
     "entrance_exams": ["JEE Advanced"], "description": "Premier technical university, IIT system flagship."},
    {"slug": "iit-delhi", "name": "IIT Delhi", "type": "engineering", "location": "New Delhi",
     "nirf_rank": 2, "naac_grade": "A++", "established": 1961, "fees_per_year_inr": 220000,
     "website": "https://home.iitd.ac.in", "notable_for": ["CS", "Electrical", "MBA"],
     "placements": {"avg_package_lpa": 26, "highest_package_lpa": 2200, "placement_pct": 96},
     "entrance_exams": ["JEE Advanced"], "description": "Top IIT for placements, situated in capital."},
    {"slug": "iit-madras", "name": "IIT Madras", "type": "engineering", "location": "Chennai, Tamil Nadu",
     "nirf_rank": 1, "naac_grade": "A++", "established": 1959, "fees_per_year_inr": 220000,
     "website": "https://www.iitm.ac.in", "notable_for": ["CS", "Mechanical", "Research"],
     "placements": {"avg_package_lpa": 24, "highest_package_lpa": 1800, "placement_pct": 94},
     "entrance_exams": ["JEE Advanced"], "description": "Ranked #1 in India consistently. Strong research output."},
    {"slug": "aiims-delhi", "name": "AIIMS New Delhi", "type": "medical", "location": "New Delhi",
     "nirf_rank": 1, "naac_grade": "A++", "established": 1956, "fees_per_year_inr": 6000,
     "website": "https://www.aiims.edu", "notable_for": ["MBBS", "MD", "MS", "Research"],
     "placements": {"avg_package_lpa": 18, "highest_package_lpa": 80, "placement_pct": 99},
     "entrance_exams": ["NEET-UG"], "description": "Best medical college in India. Highly subsidised fees."},
    {"slug": "iim-ahmedabad", "name": "IIM Ahmedabad", "type": "management", "location": "Ahmedabad, Gujarat",
     "nirf_rank": 1, "naac_grade": "A++", "established": 1961, "fees_per_year_inr": 1200000,
     "website": "https://www.iima.ac.in", "notable_for": ["MBA", "FPM", "PGPX"],
     "placements": {"avg_package_lpa": 34, "highest_package_lpa": 120, "placement_pct": 100},
     "entrance_exams": ["CAT"], "description": "Top B-school in India. Global alumni network."},
    {"slug": "iim-bangalore", "name": "IIM Bangalore", "type": "management", "location": "Bengaluru, Karnataka",
     "nirf_rank": 2, "naac_grade": "A++", "established": 1973, "fees_per_year_inr": 1190000,
     "website": "https://www.iimb.ac.in", "notable_for": ["MBA", "PGPEM", "Research"],
     "placements": {"avg_package_lpa": 33, "highest_package_lpa": 115, "placement_pct": 100},
     "entrance_exams": ["CAT"], "description": "Strong in finance, strategy, and consulting."},
    {"slug": "du-delhi-university", "name": "Delhi University", "type": "general", "location": "New Delhi",
     "nirf_rank": 11, "naac_grade": "A++", "established": 1922, "fees_per_year_inr": 25000,
     "website": "https://www.du.ac.in", "notable_for": ["BA", "B.Com", "BSc", "Law"],
     "placements": {"avg_package_lpa": 6, "highest_package_lpa": 40, "placement_pct": 70},
     "entrance_exams": ["CUET"], "description": "Large central university. Top colleges: SRCC, Hindu, St. Stephens."},
    {"slug": "bits-pilani", "name": "BITS Pilani", "type": "engineering", "location": "Pilani, Rajasthan",
     "nirf_rank": 25, "naac_grade": "A", "established": 1964, "fees_per_year_inr": 520000,
     "website": "https://www.bits-pilani.ac.in", "notable_for": ["CS", "Chemical", "Pharmacy"],
     "placements": {"avg_package_lpa": 18, "highest_package_lpa": 120, "placement_pct": 90},
     "entrance_exams": ["BITSAT"], "description": "Best private engineering college. Strong internship programme."},
    {"slug": "nit-trichy", "name": "NIT Trichy", "type": "engineering", "location": "Tiruchirappalli, Tamil Nadu",
     "nirf_rank": 8, "naac_grade": "A++", "established": 1964, "fees_per_year_inr": 150000,
     "website": "https://www.nitt.edu", "notable_for": ["CS", "Civil", "Mechanical"],
     "placements": {"avg_package_lpa": 14, "highest_package_lpa": 80, "placement_pct": 88},
     "entrance_exams": ["JEE Main"], "description": "Top NIT. Known for discipline and strong industry connections."},
    {"slug": "jadavpur-university", "name": "Jadavpur University", "type": "engineering", "location": "Kolkata, West Bengal",
     "nirf_rank": 12, "naac_grade": "A++", "established": 1955, "fees_per_year_inr": 10000,
     "website": "https://jadavpur.edu", "notable_for": ["CS", "Electronics", "Architecture"],
     "placements": {"avg_package_lpa": 12, "highest_package_lpa": 60, "placement_pct": 85},
     "entrance_exams": ["WBJEE", "JEE Main"], "description": "Highly affordable top-ranked engineering university."},
]

STUDY_ABROAD_UNIVERSITIES = [
    {"slug": "mit", "name": "MIT", "country": "USA", "qs_rank": 1,
     "tuition_per_year_usd": 57986, "notable_for": ["CS", "Engineering", "Physics", "Economics"],
     "acceptance_rate_pct": 4, "avg_gre": 330, "avg_gpa": 3.9,
     "scholarships_available": True, "description": "World's top technical university."},
    {"slug": "stanford", "name": "Stanford University", "country": "USA", "qs_rank": 3,
     "tuition_per_year_usd": 61731, "notable_for": ["CS", "MBA", "Medicine", "Law"],
     "acceptance_rate_pct": 4, "avg_gre": 329, "avg_gpa": 3.9,
     "scholarships_available": True, "description": "Silicon Valley's academic home. Top for entrepreneurship."},
    {"slug": "oxford", "name": "University of Oxford", "country": "UK", "qs_rank": 4,
     "tuition_per_year_usd": 37000, "notable_for": ["Law", "PPE", "Medicine", "Humanities"],
     "acceptance_rate_pct": 17, "avg_gre": None, "avg_gpa": 3.7,
     "scholarships_available": True, "description": "Oldest English-speaking university. Rhodes Scholarships available."},
    {"slug": "nus", "name": "National University of Singapore", "country": "Singapore", "qs_rank": 8,
     "tuition_per_year_usd": 18000, "notable_for": ["CS", "Business", "Engineering", "Medicine"],
     "acceptance_rate_pct": 20, "avg_gre": 320, "avg_gpa": 3.7,
     "scholarships_available": True, "description": "Asia's top university. Strong industry links in Singapore."},
    {"slug": "tu-munich", "name": "TU Munich", "country": "Germany", "qs_rank": 37,
     "tuition_per_year_usd": 600, "notable_for": ["Engineering", "CS", "MBA"],
     "acceptance_rate_pct": 35, "avg_gre": None, "avg_gpa": 3.5,
     "scholarships_available": True, "description": "Near-free tuition. Top German technical university."},
    {"slug": "toronto", "name": "University of Toronto", "country": "Canada", "qs_rank": 21,
     "tuition_per_year_usd": 28000, "notable_for": ["CS", "Medical Sciences", "Law", "Business"],
     "acceptance_rate_pct": 43, "avg_gre": 320, "avg_gpa": 3.7,
     "scholarships_available": True, "description": "Canada's top university. Post-study work visa friendly."},
]

PROGRAMS = [
    {"slug": "btech-cs", "name": "B.Tech Computer Science", "level": "undergraduate",
     "duration_years": 4, "avg_fees_inr": 180000, "domains": ["technology"],
     "top_recruiters": ["Google", "Microsoft", "Amazon", "Infosys", "TCS"],
     "avg_package_lpa": 18, "entrance_exams": ["JEE Main", "JEE Advanced", "BITSAT"]},
    {"slug": "mbbs", "name": "MBBS", "level": "undergraduate", "duration_years": 5,
     "avg_fees_inr": 50000, "domains": ["healthcare"],
     "top_recruiters": ["AIIMS", "Fortis", "Apollo", "Government Hospitals"],
     "avg_package_lpa": 12, "entrance_exams": ["NEET-UG"]},
    {"slug": "mba", "name": "MBA", "level": "postgraduate", "duration_years": 2,
     "avg_fees_inr": 1200000, "domains": ["management", "finance", "marketing"],
     "top_recruiters": ["McKinsey", "BCG", "Goldman Sachs", "Unilever", "Amazon"],
     "avg_package_lpa": 30, "entrance_exams": ["CAT", "XAT", "GMAT"]},
    {"slug": "bcom-honours", "name": "B.Com Honours", "level": "undergraduate",
     "duration_years": 3, "avg_fees_inr": 20000, "domains": ["finance", "accounting"],
     "top_recruiters": ["Big 4 (EY/PwC/Deloitte/KPMG)", "Banks", "Insurance Firms"],
     "avg_package_lpa": 6, "entrance_exams": ["CUET"]},
    {"slug": "bdes-design", "name": "B.Des Design", "level": "undergraduate",
     "duration_years": 4, "avg_fees_inr": 200000, "domains": ["design"],
     "top_recruiters": ["Adobe", "Flipkart", "Swiggy", "Design Agencies"],
     "avg_package_lpa": 10, "entrance_exams": ["NATA", "UCEED", "NID DAT"]},
    {"slug": "mtech-ai-ml", "name": "M.Tech AI/ML", "level": "postgraduate",
     "duration_years": 2, "avg_fees_inr": 220000, "domains": ["technology", "data_science"],
     "top_recruiters": ["Google", "Microsoft Research", "Amazon", "NVIDIA"],
     "avg_package_lpa": 30, "entrance_exams": ["GATE"]},
    {"slug": "bsc-data-science", "name": "B.Sc Data Science", "level": "undergraduate",
     "duration_years": 3, "avg_fees_inr": 80000, "domains": ["data_science"],
     "top_recruiters": ["Flipkart", "Analytics firms", "Startups"],
     "avg_package_lpa": 10, "entrance_exams": ["CUET", "University entrance"]},
]

SCHOLARSHIPS = [
    {"slug": "gates-cambridge", "name": "Gates Cambridge Scholarship",
     "provider": "Bill & Melinda Gates Foundation", "country": "UK",
     "value_usd": 60000, "value_description": "Full funding for postgraduate study at Cambridge",
     "eligibility": ["Non-UK student", "Admission to Cambridge postgraduate programme"],
     "deadline_month": 10, "renewable": True, "merit_based": True, "need_based": False,
     "fields": ["Any discipline"], "url": "https://www.gatescambridge.org"},
    {"slug": "inlaks-scholarship", "name": "Inlaks Shivdasani Scholarship",
     "provider": "Inlaks Foundation", "country": "Abroad (USA/UK/Europe)",
     "value_usd": 100000, "value_description": "Up to $100,000 for study abroad",
     "eligibility": ["Indian citizen", "Below 30 years", "Admission to top 50 world university"],
     "deadline_month": 3, "renewable": False, "merit_based": True, "need_based": False,
     "fields": ["Any discipline except MBA"], "url": "https://www.inlaksfoundation.org"},
    {"slug": "dst-inspire", "name": "DST INSPIRE Scholarship",
     "provider": "Department of Science & Technology, India", "country": "India",
     "value_inr": 80000, "value_description": "Rs 80,000/year for BSc/BS top 1% students",
     "eligibility": ["Top 1% in Class 12", "Enrolled in Natural Sciences at recognised college"],
     "deadline_month": 9, "renewable": True, "merit_based": True, "need_based": False,
     "fields": ["Natural Sciences"], "url": "https://online-inspire.gov.in"},
    {"slug": "aicte-pragati", "name": "AICTE Pragati Scholarship",
     "provider": "AICTE", "country": "India",
     "value_inr": 50000, "value_description": "Rs 30,000 per year + Rs 2,000/month allowance",
     "eligibility": ["Female student", "Family income < 8 LPA", "Enrolled in AICTE-approved institution"],
     "deadline_month": 11, "renewable": True, "merit_based": False, "need_based": True,
     "fields": ["Engineering", "Technology", "Pharmacy"], "url": "https://www.aicte-india.org"},
    {"slug": "fulbright-nehru", "name": "Fulbright-Nehru Master's Fellowship",
     "provider": "USIEF", "country": "USA",
     "value_usd": 70000, "value_description": "Full funding: tuition + living + travel for US Master's",
     "eligibility": ["Indian citizen", "Bachelor's degree", "3+ years work experience", "Strong academic record"],
     "deadline_month": 6, "renewable": False, "merit_based": True, "need_based": False,
     "fields": ["Arts", "Science", "Commerce", "Policy — except MBA/Medicine"],
     "url": "https://www.usief.org.in"},
    {"slug": "jn-tata-endowment", "name": "JN Tata Endowment Loan Scholarship",
     "provider": "JN Tata Endowment", "country": "Abroad",
     "value_inr": 1000000, "value_description": "Up to Rs 10 lakh interest-free loan + gift portion",
     "eligibility": ["Indian citizen", "Admission abroad", "Strong academic + extracurricular record"],
     "deadline_month": 2, "renewable": False, "merit_based": True, "need_based": False,
     "fields": ["Any discipline"], "url": "https://www.jntataendowment.org"},
    {"slug": "pm-scholarship-scheme", "name": "PM Scholarship Scheme",
     "provider": "Ministry of Home Affairs, India", "country": "India",
     "value_inr": 36000, "value_description": "Rs 36,000/year for wards of Ex-servicemen",
     "eligibility": ["Ward/widow of Ex-serviceman", "60%+ in Class 12", "Professional course"],
     "deadline_month": 12, "renewable": True, "merit_based": False, "need_based": True,
     "fields": ["Engineering", "Medical", "MBA", "MCA"], "url": "https://desw.gov.in"},
    {"slug": "dhirubhai-ambani", "name": "Dhirubhai Ambani Scholarship",
     "provider": "Reliance Foundation", "country": "India",
     "value_inr": 200000, "value_description": "Rs 2 lakh/year for 4 years",
     "eligibility": ["Top 0.1% in Class 12", "Enrolled in accredited Indian institution", "Family income < 6 LPA"],
     "deadline_month": 8, "renewable": True, "merit_based": True, "need_based": True,
     "fields": ["Engineering", "CS", "Economics", "Natural Sciences"],
     "url": "https://www.reliancefoundation.org"},
]

EXAM_CUTOFFS = {
    "JEE Advanced": {
        "exam_name": "JEE Advanced",
        "for_admission_to": "IITs",
        "cutoff_by_rank": {
            "IIT Bombay CS": {"general": 67, "obc": 350, "sc": 800, "st": 500},
            "IIT Delhi CS": {"general": 50, "obc": 280, "sc": 750, "st": 480},
            "IIT Madras CS": {"general": 80, "obc": 420, "sc": 900, "st": 600},
            "IIT Bombay Electrical": {"general": 150, "obc": 750, "sc": 1200, "st": 800},
            "IIT Delhi Mechanical": {"general": 700, "obc": 2000, "sc": 3500, "st": 2500},
        },
        "note": "Rank is AIR (All India Rank). Lower rank = better.",
    },
    "JEE Main": {
        "exam_name": "JEE Main",
        "for_admission_to": "NITs, IIITs, GFTIs",
        "cutoff_by_percentile": {
            "NIT Trichy CS": {"general": 99.5, "obc": 98.5, "sc": 95, "st": 90},
            "NIT Surathkal CS": {"general": 99.2, "obc": 98.0, "sc": 94, "st": 88},
            "NIT Warangal CS": {"general": 99.3, "obc": 98.2, "sc": 94.5, "st": 89},
            "IIIT Hyderabad CS": {"general": 99.6, "obc": 99.0, "sc": 96, "st": 92},
        },
        "note": "Percentile score. Higher = better.",
    },
    "NEET-UG": {
        "exam_name": "NEET-UG",
        "for_admission_to": "MBBS/BDS across India",
        "cutoff_by_score": {
            "AIIMS Delhi MBBS": {"general": 715, "obc": 700, "sc": 680, "st": 660},
            "Government Medical College (Any State)": {"general": 600, "obc": 580, "sc": 530, "st": 500},
            "Private Medical College": {"general": 480, "obc": 460, "sc": 420, "st": 400},
        },
        "note": "Score out of 720. Higher = better.",
    },
    "CAT": {
        "exam_name": "CAT",
        "for_admission_to": "IIMs and top B-schools",
        "cutoff_by_percentile": {
            "IIM Ahmedabad": {"general": 99.5, "obc": 99.0, "sc": 97, "st": 95},
            "IIM Bangalore": {"general": 99.5, "obc": 99.0, "sc": 97, "st": 95},
            "IIM Calcutta": {"general": 99.0, "obc": 98.5, "sc": 96, "st": 93},
            "IIM Lucknow": {"general": 97.0, "obc": 95.0, "sc": 90, "st": 85},
            "MDI Gurgaon": {"general": 95.0, "obc": 92.0, "sc": 85, "st": 80},
        },
        "note": "Overall percentile. Individual section cut-offs also apply.",
    },
    "CUET": {
        "exam_name": "CUET",
        "for_admission_to": "Central Universities (DU, BHU, JNU, etc.)",
        "cutoff_by_score": {
            "DU SRCC B.Com Honours": {"general": 95, "obc": 88, "sc": 80, "st": 75},
            "DU Hindu College BA (H) Economics": {"general": 94, "obc": 86, "sc": 78, "st": 73},
            "BHU BA English": {"general": 88, "obc": 80, "sc": 72, "st": 68},
            "JNU MA Political Science": {"general": 90, "obc": 82, "sc": 75, "st": 70},
        },
        "note": "Normalised score out of 100.",
    },
}
