# Generated by Django 6.0.6 on 2026-06-12 09:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('career_counselling', 'Career Counselling'), ('university_admissions', 'University Admissions'), ('study_abroad', 'Study Abroad'), ('career_intelligence', 'Career Intelligence'), ('ai_guidance', 'AI Guidance'), ('follow_up', 'Follow-up')], default='career_counselling', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled_student', 'Cancelled by Student'), ('cancelled_counsellor', 'Cancelled by Counsellor'), ('no_show', 'No Show')], default='pending', max_length=30)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('meeting_link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('student_feedback', models.TextField(blank=True)),
                ('student_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('counsellor_notes', models.TextField(blank=True)),
                ('recording_url', models.URLField(blank=True)),
                ('is_free_session', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
