# Generated by Django 6.0.6 on 2026-06-12 10:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictorResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_type', models.CharField(choices=[('JEE Main', 'JEE Main'), ('JEE Advanced', 'JEE Advanced'), ('NEET-UG', 'NEET-UG'), ('CAT', 'CAT'), ('CUET', 'CUET'), ('GATE', 'GATE'), ('XAT', 'XAT'), ('BITSAT', 'BITSAT')], max_length=20)),
                ('score', models.FloatField()),
                ('category', models.CharField(choices=[('general', 'General'), ('obc', 'OBC'), ('sc', 'SC'), ('st', 'ST'), ('ews', 'EWS')], default='general', max_length=10)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('predicted_colleges', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictor_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
