# Generated by Django 6.0.6 on 2026-06-12 10:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('career_match', 'Career Match'), ('skill_gap', 'Skill Gap'), ('learning_path', 'Learning Path'), ('market_trend', 'Market Trend'), ('salary_insight', 'Salary Insight')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-relevance_score', '-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='CareerRoadmap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_career', models.CharField(max_length=200)),
                ('plan_3_months', models.JSONField(default=list)),
                ('plan_6_months', models.JSONField(default=list)),
                ('plan_1_year', models.JSONField(default=list)),
                ('plan_3_years', models.JSONField(default=list)),
                ('plan_5_years', models.JSONField(default=list)),
                ('progress_notes', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to='students.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_type', models.CharField(choices=[('interest', 'Interest Assessment'), ('personality', 'Personality Assessment'), ('aptitude', 'Aptitude Assessment'), ('readiness', 'Career Readiness')], max_length=20)),
                ('responses', models.JSONField(default=dict)),
                ('scores', models.JSONField(default=dict)),
                ('result_summary', models.TextField(blank=True)),
                ('top_careers', models.JSONField(default=list)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-completed_at'],
                'unique_together': {('student', 'assessment_type')},
            },
        ),
    ]
