# Generated by Django 6.0.6 on 2026-06-14 16:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIVideoInterviewQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('category', models.CharField(choices=[('intro', 'Introduction'), ('behavioral', 'Behavioral'), ('situational', 'Situational'), ('technical', 'Technical'), ('motivation', 'Motivation')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('ideal_answer_keywords', models.JSONField(default=list)),
                ('time_limit_seconds', models.PositiveSmallIntegerField(default=120)),
                ('tips', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnterpriseClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('client_type', models.CharField(choices=[('school', 'School'), ('university', 'University'), ('corporate', 'Corporate'), ('government', 'Government Institution'), ('ngo', 'NGO / Non-profit')], max_length=20)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('license_type', models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('scale', 'Scale'), ('unlimited', 'Unlimited')], default='starter', max_length=20)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('max_users', models.PositiveIntegerField(default=50)),
                ('current_users', models.PositiveIntegerField(default=0)),
                ('contract_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceCounsellorScript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(choices=[('career_intro', 'Career Introduction'), ('stream_selection', 'Stream Selection'), ('college_options', 'College Options'), ('exam_prep', 'Exam Preparation'), ('skill_building', 'Skill Building'), ('placement_ready', 'Placement Readiness')], max_length=30, unique=True)),
                ('script_text', models.TextField()),
                ('follow_up_questions', models.JSONField(default=list)),
                ('response_templates', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AICareerTwinSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_context', models.JSONField(default=dict)),
                ('career_profile_snapshot', models.JSONField(default=dict)),
                ('recommendations', models.JSONField(default=list)),
                ('action_plan', models.JSONField(default=list)),
                ('predicted_placement_score', models.PositiveSmallIntegerField(default=0)),
                ('predicted_career_fit', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='ai_twin_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIPlacementPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placement_probability', models.FloatField(default=0.0)),
                ('predicted_package_min', models.PositiveIntegerField(blank=True, null=True)),
                ('predicted_package_max', models.PositiveIntegerField(blank=True, null=True)),
                ('top_matching_companies', models.JSONField(default=list)),
                ('skill_gap_impact', models.JSONField(default=dict)),
                ('timeline_to_ready', models.PositiveSmallIntegerField(default=6)),
                ('model_inputs', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='placement_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
